services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: corretora
      POSTGRES_USER: corretora
      POSTGRES_PASSWORD: corretora
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./infra/postgres/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_duration_statement=0"]

volumes:
  postgres_data: